"""
Pending order models for the Order Approval Dashboard.

PRD: specs/prd-order-dashboard.md
"""

import uuid
from datetime import datetime, date
from decimal import Decimal

from sqlalchemy import (
    Column, String, DateTime, Date, JSON, Integer, Text,
    Numeric, ForeignKey, Index
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from ..db import Base


class PendingOrder(Base):
    """Order generated by A1 workflow, awaiting approval."""

    __tablename__ = "pending_orders"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Source tracking
    contract_number = Column(String(50), nullable=False)
    customer_number = Column(String(50), nullable=False, index=True)
    customer_name = Column(String(255))
    customer_info = Column(JSON, nullable=True)  # Populated from Upsales via A2 + Fix3
    # Expected: {"phone": "+46...", "email": "...", "address1": "...", "city": "...", "zip": "...", "country": "SE"}
    source = Column(String(20), nullable=False, default="recurring")  # 'recurring' | 'new'

    # Full Fortnox Order payload (ready to POST)
    order_payload = Column(JSON, nullable=False)

    # Denormalized display fields (for fast table rendering)
    delivery_date = Column(Date, nullable=False)
    order_date = Column(Date)
    total_amount = Column(Numeric(12, 2))
    currency = Column(String(10), default="SEK")
    item_count = Column(Integer)
    item_summary = Column(Text)  # e.g. "3x Mensskydd Tena, 2x Tvattlapp"

    # Enrichment fields
    administration_fee = Column(Numeric(12, 2), default=0)
    freight = Column(Numeric(12, 2), default=0)
    remarks = Column(Text)
    period_start = Column(Date)
    period_end = Column(Date, nullable=True)
    interval = Column(String(50), nullable=True)  # e.g. "Kvartal", "Halvår", "Helår"
    invoice_interval = Column(Integer, nullable=True)  # Months: 3, 6, 12. NULL = no subscription.

    # Workflow state
    status = Column(String(20), nullable=False, default="pending", index=True)
    # Values: 'pending', 'approved', 'denied', 'created', 'failed', 'deleted'

    # Duplicate prevention
    your_order_number = Column(String(100), unique=True, nullable=False, index=True)

    # Post-creation tracking
    fortnox_order_number = Column(String(50))
    error_message = Column(Text)

    # Timestamps
    generated_at = Column(DateTime, default=datetime.utcnow)
    reviewed_at = Column(DateTime)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    approval_logs = relationship("ApprovalLog", back_populates="order", order_by="ApprovalLog.created_at.desc()")

    __table_args__ = (
        Index("idx_pending_orders_status_source", "status", "source"),
        Index("idx_pending_orders_delivery_date", "delivery_date"),
    )


class ApprovalLog(Base):
    """Audit trail for all actions on pending orders."""

    __tablename__ = "approval_log"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    order_id = Column(UUID(as_uuid=True), ForeignKey("pending_orders.id"), nullable=False, index=True)
    action = Column(String(20), nullable=False)  # 'approved', 'denied', 'edited', 'created', 'failed'
    performed_by = Column(String(100))
    details = Column(JSON)  # What changed (for edits)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    order = relationship("PendingOrder", back_populates="approval_logs")
