"""
API Client Template

Copy this template and customize for each service.
Replace placeholders marked with {PLACEHOLDER}.

Generated by api-boilerplate skill.
"""

from datetime import datetime
from typing import Any, TypeVar
import httpx
from pydantic import BaseModel


# =============================================================================
# Configuration
# =============================================================================

BASE_URL = "{BASE_URL}"  # e.g., "https://api.example.com/v1"
AUTH_METHOD = "{AUTH_METHOD}"  # "api_key" | "oauth2" | "basic"


# =============================================================================
# Exceptions
# =============================================================================

class APIError(Exception):
    """Base exception for API errors."""

    def __init__(self, status_code: int, message: str, details: dict | None = None):
        self.status_code = status_code
        self.message = message
        self.details = details or {}
        super().__init__(f"[{status_code}] {message}")


class AuthenticationError(APIError):
    """401 Unauthorized - Invalid or expired credentials."""
    pass


class NotFoundError(APIError):
    """404 Not Found - Resource does not exist."""
    pass


class ValidationError(APIError):
    """400 Bad Request - Invalid request data."""
    pass


class RateLimitError(APIError):
    """429 Too Many Requests - Rate limit exceeded."""
    pass


# =============================================================================
# Models (customize per service)
# =============================================================================

class BaseResponse(BaseModel):
    """Base model for API responses."""
    pass


# Example models - replace with actual service models:

# class Customer(BaseModel):
#     id: str
#     name: str
#     email: str | None = None
#     created_at: datetime | None = None
#
# class CreateCustomerRequest(BaseModel):
#     name: str
#     email: str | None = None


# =============================================================================
# Client
# =============================================================================

T = TypeVar("T", bound=BaseModel)


class APIClient:
    """
    {SERVICE_NAME} API Client

    Usage:
        client = APIClient(api_key="your-key")
        customers = client.list_customers()
    """

    def __init__(
        self,
        # Auth parameters - uncomment the one you need:
        api_key: str | None = None,
        # access_token: str | None = None,
        # refresh_token: str | None = None,
        # username: str | None = None,
        # password: str | None = None,
        timeout: float = 30.0,
    ):
        self.base_url = BASE_URL.rstrip("/")
        self._api_key = api_key
        self._timeout = timeout

        # Configure headers based on auth method
        headers = {
            "Content-Type": "application/json",
            "Accept": "application/json",
        }

        # API Key auth
        if api_key:
            headers["Authorization"] = f"Bearer {api_key}"
            # Or for header-based key:
            # headers["X-API-Key"] = api_key

        self._client = httpx.Client(
            base_url=self.base_url,
            headers=headers,
            timeout=timeout,
        )

    def close(self):
        """Close the HTTP client."""
        self._client.close()

    def __enter__(self):
        return self

    def __exit__(self, *args):
        self.close()

    # -------------------------------------------------------------------------
    # Core HTTP methods
    # -------------------------------------------------------------------------

    def _request(
        self,
        method: str,
        path: str,
        params: dict | None = None,
        json: dict | None = None,
    ) -> dict[str, Any]:
        """Make an HTTP request and handle errors."""
        try:
            response = self._client.request(
                method=method,
                url=path,
                params=params,
                json=json,
            )
            return self._handle_response(response)
        except httpx.TimeoutException as e:
            raise APIError(408, f"Request timeout: {e}")
        except httpx.RequestError as e:
            raise APIError(0, f"Request failed: {e}")

    def _handle_response(self, response: httpx.Response) -> dict[str, Any]:
        """Handle API response and raise appropriate errors."""
        if response.status_code == 204:
            return {}

        try:
            data = response.json()
        except Exception:
            data = {"raw": response.text}

        if response.is_success:
            return data

        # Error handling
        error_message = data.get("message", data.get("error", response.text))

        if response.status_code == 401:
            raise AuthenticationError(401, error_message, data)
        elif response.status_code == 404:
            raise NotFoundError(404, error_message, data)
        elif response.status_code == 400:
            raise ValidationError(400, error_message, data)
        elif response.status_code == 429:
            raise RateLimitError(429, error_message, data)
        else:
            raise APIError(response.status_code, error_message, data)

    # -------------------------------------------------------------------------
    # Resource methods (customize per service)
    # -------------------------------------------------------------------------

    # Example CRUD methods - replace with actual endpoints:

    # def list_customers(self, page: int = 1, limit: int = 100) -> list[Customer]:
    #     """List all customers."""
    #     data = self._request("GET", "/customers", params={"page": page, "limit": limit})
    #     return [Customer.model_validate(c) for c in data.get("customers", [])]
    #
    # def get_customer(self, customer_id: str) -> Customer:
    #     """Get a customer by ID."""
    #     data = self._request("GET", f"/customers/{customer_id}")
    #     return Customer.model_validate(data["customer"])
    #
    # def create_customer(self, customer: CreateCustomerRequest) -> Customer:
    #     """Create a new customer."""
    #     data = self._request("POST", "/customers", json=customer.model_dump(exclude_none=True))
    #     return Customer.model_validate(data["customer"])
    #
    # def update_customer(self, customer_id: str, customer: CreateCustomerRequest) -> Customer:
    #     """Update an existing customer."""
    #     data = self._request("PUT", f"/customers/{customer_id}", json=customer.model_dump(exclude_none=True))
    #     return Customer.model_validate(data["customer"])
    #
    # def delete_customer(self, customer_id: str) -> None:
    #     """Delete a customer."""
    #     self._request("DELETE", f"/customers/{customer_id}")


# =============================================================================
# Usage Example
# =============================================================================

if __name__ == "__main__":
    # Example usage
    # client = APIClient(api_key="your-api-key")
    # customers = client.list_customers()
    # print(f"Found {len(customers)} customers")
    pass
