#!/usr/bin/env python3
# /// script
# dependencies = ["pyyaml"]
# ///
"""
Scans all client spec folders and generates spec-data.js for spec-pipeline.html.

Usage:
    uv run workspace/playgrounds/generate-spec-data.py

Output:
    workspace/playgrounds/spec-data.js  (auto-generated, do not edit manually)
"""

import json
import re
import sys
from pathlib import Path

import yaml

SCRIPT_DIR = Path(__file__).parent
WORKSPACE_DIR = SCRIPT_DIR.parent          # workspace/
CLIENTS_DIR = WORKSPACE_DIR / "clients"
CONFIG_FILE = SCRIPT_DIR / "clients.json"
OUTPUT_FILE = SCRIPT_DIR / "spec-data.js"

STAGE_FOLDERS = ["1-spec", "2-build", "3-test", "4-live"]

# Fallback color palette for clients not in clients.json
COLOR_PALETTE = [
    "#2563eb", "#f97316", "#7c3aed", "#059669",
    "#dc2626", "#0891b2", "#d97706", "#0f766e",
]


def parse_frontmatter(content: str) -> dict:
    """Extract and parse YAML frontmatter from markdown content."""
    match = re.match(r"^---\s*\n(.*?)\n---\s*\n", content, re.DOTALL)
    if not match:
        return {}
    try:
        return yaml.safe_load(match.group(1)) or {}
    except yaml.YAMLError as e:
        print(f"  Warning: YAML parse error: {e}", file=sys.stderr)
        return {}


def title_case(name: str) -> str:
    """Convert kebab-case to Title Case."""
    return " ".join(word.capitalize() for word in name.split("-"))


def load_client_config() -> dict:
    if CONFIG_FILE.exists():
        with open(CONFIG_FILE) as f:
            return json.load(f)
    return {}


def main():
    client_config = load_client_config()

    if not CLIENTS_DIR.exists():
        print(f"Error: Clients directory not found: {CLIENTS_DIR}", file=sys.stderr)
        sys.exit(1)

    clients = []
    client_folders = sorted(d for d in CLIENTS_DIR.iterdir() if d.is_dir())

    for i, client_dir in enumerate(client_folders):
        client_name = client_dir.name
        specs_dir = client_dir / "specs"

        if not specs_dir.exists():
            continue

        config = client_config.get(client_name, {})
        label = config.get("label", title_case(client_name))
        color = config.get("color", COLOR_PALETTE[i % len(COLOR_PALETTE)])

        specs = []

        for stage_folder in STAGE_FOLDERS:
            stage_dir = specs_dir / stage_folder
            if not stage_dir.exists():
                continue

            for spec_file in sorted(stage_dir.glob("*.md")):
                if spec_file.name.upper() == "README.MD":
                    continue

                content = spec_file.read_text(encoding="utf-8")
                fm = parse_frontmatter(content)

                if not fm:
                    print(f"  Skipping (no frontmatter): {client_name}/{stage_folder}/{spec_file.name}", file=sys.stderr)
                    continue

                # Normalise systems to a flat list of strings
                raw_systems = fm.get("systems") or []
                if isinstance(raw_systems, str):
                    raw_systems = [raw_systems]
                systems = [str(s) for s in raw_systems]

                specs.append({
                    "id": str(fm.get("id", "")),
                    "name": str(fm.get("name", spec_file.stem)),
                    "type": str(fm.get("type", "automation")),
                    "stage_folder": stage_folder,
                    "orchestrator": str(fm.get("orchestrator", "tbd")),
                    "systems": systems,
                    "needs_fixes": bool(fm.get("needs_fixes", False)),
                    "filename": spec_file.name,
                })

        if specs:
            clients.append({
                "name": client_name,
                "label": label,
                "color": color,
                "specs": specs,
            })
            print(f"  {label}: {len(specs)} specs")

    data = {"clients": clients}
    total = sum(len(c["specs"]) for c in clients)

    js = (
        "// Auto-generated by generate-spec-data.py — do not edit manually.\n"
        "// Run:  uv run workspace/playgrounds/generate-spec-data.py\n"
        f"const DATA = {json.dumps(data, indent=2, ensure_ascii=False)};\n"
    )
    OUTPUT_FILE.write_text(js, encoding="utf-8")

    print(f"\n✓ {OUTPUT_FILE.relative_to(WORKSPACE_DIR.parent)}")
    print(f"  {len(clients)} clients · {total} specs")


if __name__ == "__main__":
    main()
