# /// script
# requires-python = ">=3.11"
# dependencies = ["resend", "markdown"]
# ///
"""
Send a markdown digest as a styled HTML email via Resend API.

Usage:
    uv run scripts/send-digest-email.py --to user@example.com --subject "Subject" --body-file digest.md
    uv run scripts/send-digest-email.py --to user@example.com --subject "Subject" --body "# Hello"

Environment variables:
    RESEND_API_KEY      - Required. Resend API key.
    DIGEST_FROM_EMAIL   - Required. Verified sender address.
"""

import argparse
import os
import sys
from pathlib import Path

import markdown
import resend

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    line-height: 1.6;
    color: #1a1a1a;
    max-width: 700px;
    margin: 0 auto;
    padding: 20px;
    background: #f8f9fa;
  }}
  .container {{
    background: #ffffff;
    border-radius: 8px;
    padding: 32px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
  }}
  h1 {{
    color: #1a1a1a;
    border-bottom: 2px solid #e9ecef;
    padding-bottom: 8px;
    font-size: 24px;
  }}
  h2 {{
    color: #333;
    margin-top: 28px;
    font-size: 20px;
  }}
  h3 {{
    color: #555;
    font-size: 16px;
  }}
  table {{
    border-collapse: collapse;
    width: 100%;
    margin: 16px 0;
    font-size: 14px;
  }}
  th, td {{
    border: 1px solid #dee2e6;
    padding: 8px 12px;
    text-align: left;
  }}
  th {{
    background: #f1f3f5;
    font-weight: 600;
  }}
  tr:nth-child(even) {{
    background: #f8f9fa;
  }}
  code {{
    background: #f1f3f5;
    padding: 2px 6px;
    border-radius: 3px;
    font-size: 13px;
    font-family: 'SF Mono', Monaco, 'Cascadia Code', monospace;
  }}
  pre {{
    background: #f1f3f5;
    padding: 16px;
    border-radius: 6px;
    overflow-x: auto;
    font-size: 13px;
  }}
  pre code {{
    background: none;
    padding: 0;
  }}
  blockquote {{
    border-left: 4px solid #4dabf7;
    margin: 16px 0;
    padding: 8px 16px;
    background: #e7f5ff;
    border-radius: 0 4px 4px 0;
  }}
  ul, ol {{
    padding-left: 24px;
  }}
  li {{
    margin: 4px 0;
  }}
  .footer {{
    margin-top: 32px;
    padding-top: 16px;
    border-top: 1px solid #e9ecef;
    font-size: 12px;
    color: #868e96;
    text-align: center;
  }}
</style>
</head>
<body>
<div class="container">
{content}
<div class="footer">
  Generated by Agentic Ops &middot; System Digest
</div>
</div>
</body>
</html>
"""


def markdown_to_html(md_text: str) -> str:
    """Convert markdown to styled HTML email."""
    html_content = markdown.markdown(
        md_text,
        extensions=["tables", "fenced_code", "codehilite"],
    )
    return HTML_TEMPLATE.format(content=html_content)


def send_email(to: str, subject: str, html_body: str) -> dict:
    """Send an HTML email via Resend API."""
    api_key = os.environ.get("RESEND_API_KEY")
    if not api_key:
        print("Error: RESEND_API_KEY environment variable is not set.", file=sys.stderr)
        print("Set it in your .env file or export it:", file=sys.stderr)
        print("  export RESEND_API_KEY=re_xxxxxxxxxxxxx", file=sys.stderr)
        sys.exit(1)

    from_email = os.environ.get("DIGEST_FROM_EMAIL")
    if not from_email:
        print("Error: DIGEST_FROM_EMAIL environment variable is not set.", file=sys.stderr)
        print("Set it to a verified sender address in Resend.", file=sys.stderr)
        sys.exit(1)

    resend.api_key = api_key

    params: resend.Emails.SendParams = {
        "from": from_email,
        "to": [to],
        "subject": subject,
        "html": html_body,
    }

    result = resend.Emails.send(params)
    return result


def main():
    parser = argparse.ArgumentParser(description="Send a markdown digest as HTML email via Resend")
    parser.add_argument("--to", required=True, help="Recipient email address")
    parser.add_argument("--subject", required=True, help="Email subject line")
    parser.add_argument("--body-file", help="Path to markdown file to send")
    parser.add_argument("--body", help="Inline markdown content to send")
    parser.add_argument("--save-html", help="Also save the HTML to this path")
    args = parser.parse_args()

    # Read markdown content
    if args.body_file:
        md_text = Path(args.body_file).read_text(encoding="utf-8")
    elif args.body:
        md_text = args.body
    else:
        print("Error: provide either --body-file or --body", file=sys.stderr)
        sys.exit(1)

    # Convert to HTML
    html_body = markdown_to_html(md_text)

    # Optionally save HTML
    if args.save_html:
        Path(args.save_html).write_text(html_body, encoding="utf-8")
        print(f"HTML saved to: {args.save_html}")

    # Send email
    result = send_email(args.to, args.subject, html_body)
    print(f"Email sent successfully. ID: {result.get('id', 'unknown')}")


if __name__ == "__main__":
    main()
